// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE


var Color = /* module */[
  /* grey */"#B2B2B2",
  /* black */"#202020",
  /* darkGrey */"#3F3F3F",
  /* white */"#ffff"
];

export {
  Color ,
  
}
/* No side effect */
